### ISSUE TITLE
Map on Dd Lab site not match map on Amazon Frontlines

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/mapa-waorani#16]
These two maps appear to be interacting a little differently. Some of the icons have text below them in our lab preview, but not when view on the Frontlines website. See example below of what happens when you click on exactly the same point on each map.

<img width="452" alt="screen shot 2017-11-20 at 14 08 12" src="https://user-images.githubusercontent.com/21277147/33022334-c1f243cc-cdfc-11e7-8b7e-26d313dee196.png">

<img width="486" alt="screen shot 2017-11-20 at 14 08 35" src="https://user-images.githubusercontent.com/21277147/33022335-c22fd0e8-cdfc-11e7-839b-898fc13e41b9.png">

**Comment by karissa** [comment]
What is the language that is being used on Amazon Frontlines?

**Comment by aliya-ryan** [comment]
Thank you Karissa - yes that's half the problem (I was comparing a Spanish version with English version map). So our en version matches the Amazon Frontlines one, which is good and it should, however there is an English translation for this kind of point so it's name should appear - but that's a separate issue, I'll close this one.
